import {
  Users,
  Bed,
  Sofa,
  Bath,
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  X,
  MapPin,
  Clock,
  Grid3x3,
  Info,
  KeyRound,
  Shield,
  Coffee,
  Sunrise,
  Moon,
  Plus,
  Minus,
  Copy,
  Star,
  Menu,
  Heart,
  Calendar,
  User,
  Building2,
  Sparkles,
  Wifi,
  Wind,
  Tv,
  Car,
  Dumbbell,
  Waves,
  Check,
  Pencil,
  type LucideProps,
} from 'lucide-react';

const map = {
  users: Users,
  bed: Bed,
  sofa: Sofa,
  bath: Bath,
  search: Search,
  chevDown: ChevronDown,
  chevLeft: ChevronLeft,
  chevRight: ChevronRight,
  x: X,
  pin: MapPin,
  clock: Clock,
  grid: Grid3x3,
  info: Info,
  key: KeyRound,
  shield: Shield,
  coffee: Coffee,
  sunrise: Sunrise,
  moon: Moon,
  plus: Plus,
  minus: Minus,
  copy: Copy,
  star: Star,
  check: Check,
  menu: Menu,
  heart: Heart,
  calendar: Calendar,
  user: User,
  building: Building2,
  sparkles: Sparkles,
  wifi: Wifi,
  wind: Wind,
  tv: Tv,
  car: Car,
  dumbbell: Dumbbell,
  waves: Waves,
  pencil: Pencil,
} as const;

export type IconName = keyof typeof map;

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName;
}

export function Icon({ name, size = 20, strokeWidth = 1.6, ...rest }: IconProps) {
  const Component = map[name];
  return <Component size={size} strokeWidth={strokeWidth} {...rest} />;
}
