import type { Building, NeighborhoodId, Property, PropertyRate, PropertyUpgrade } from '@/types';
import { CANCELLATION_POLICY } from '@/lib/policies';

/**
 * AVEXA properties — ported verbatim from stay-data-*.jsx files
 * by Claude Design handoff. All 8 suites in Bucharest City Centre.
 */

// Money of record: RON (display converts via lib/currency).
const baseUpgrades: PropertyUpgrade[] = [
  { id: 'breakfast', name: 'Breakfast', price: 105, unit: '/day/person', free: false },
  { id: 'late_checkout', name: 'Late check-out', price: 105, unit: '', free: true },
  { id: 'early_checkin', name: 'Early check-in', price: 105, unit: '', free: true },
];

// Static-fallback nightly rate in RON (used only when Supabase is down;
// live prices overlay from Hostaway via applyLivePricing). ONE rate per suite —
// cancellation is a membership right (DX7), never a rate tier (M1.1.1).
function rates(ron: number): PropertyRate[] {
  return [
    {
      id: 'standard',
      name: 'Direct rate',
      perNight: ron,
      discount: 0,
      refundable: true,
      perks: [
        'Earn AVEXA Coins on this stay',
        'Flexible cancellation for members',
        'Digital check-in, no front desk',
      ],
      highlight: CANCELLATION_POLICY.summary,
    },
  ];
}

// Lightweight neighborhood lookup — keeps the data file self-contained
// without a runtime import from lib/neighborhoods.ts. Mirror any palette
// changes between the two files.
const nbh: Record<
  NeighborhoodId,
  { label: string; color: string }
> = {
  'calea-victoriei':  { label: 'Calea Victoriei',  color: '#2E7D32' },
  'old-city-center':  { label: 'Old City Center',  color: '#B08840' },
  'universitate':     { label: 'Universitate',     color: '#1565C0' },
  'piata-romana':     { label: 'Piața Romană',     color: '#6A1B9A' },
};

/**
 * The four AVEXA buildings, in /locations display order (client-confirmed).
 * Named by street address — guests navigate by address, not by brand.
 *   Calea Victoriei 142 → 102, 202, 301, 302, 303
 *   Calea Victoriei 2   → 101, 201
 *   Colței 25           → 203
 *   Polona 115          → 304
 */
export const BUILDINGS: Building[] = [
  { id: 'cv142', name: 'Calea Victoriei 142' },
  { id: 'cv2', name: 'Calea Victoriei 2' },
  { id: 'coltei25', name: 'Colței 25' },
  { id: 'polona115', name: 'Polona 115' },
];

const sharedTagline = 'The city, effortlessly yours.';
const sharedCheckin = '3:00 PM – 12:00 AM';
const sharedCheckout = '11:00 AM';

export const properties: Property[] = [
  // ─────────────────────────────────────────────────────────────
  {
    id: '101',
    slug: 'the-little-gem',
    name: 'The Little Gem',
    subtitle: 'AVEXA Suite 101',
    tagline: sharedTagline,
    neighborhood: 'old-city-center',
    neighborhoodLabel: nbh['old-city-center'].label,
    neighborhoodColor: nbh['old-city-center'].color,
    building: 'cv2',
    address: 'Calea Victoriei Nr. 2, Sector 3, Bucharest',
    stats: [
      { icon: 'users', label: '2 Guests' },
      { icon: 'bed', label: 'Studio' },
      { icon: 'sofa', label: '1 Bed' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 2,
    metaDescription:
      'A chic studio for two inside the interwar Adriatica Palace, at the gateway to Old Town — a Bucharest city center apartment with digital check-in.',
    description:
      'A compact studio for two inside the interwar Adriatica Palace, at the very gateway to Bucharest\'s Old Town. Living greenery, a cozy double bed with fresh linens, and a sleek shower cabin keep the space calm, while the equipped kitchenette handles quick meals and coffee. Digital check-in means you arrive on your own schedule — no front desk.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/101/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/101/00-cover.jpeg' },
      { id: 2, label: 'Bedroom', src: '/listings/101/04-bedroom.jpeg' },
      { id: 3, label: 'Bathroom', src: '/listings/101/11-bathroom-shower.jpeg' },
      { id: 4, label: 'Bathroom Detail', src: '/listings/101/13-bathroom-toilet.jpeg' },
      { id: 5, label: 'Kitchenette', src: '/listings/101/14-kitchenette.jpeg' },
      { id: 6, label: 'Hallway', src: '/listings/101/16-hallway.jpeg' },
      { id: 7, label: 'Entrance', src: '/listings/101/18-entrance.jpeg' },
      { id: 8, label: 'Building Hallway', src: '/listings/101/19-building-hallway.jpeg' },
      { id: 9, label: 'Decor', src: '/listings/101/20-decor.jpeg' },
      { id: 10, label: 'Exterior View', src: '/listings/101/23-exterior.jpeg' },
      { id: 11, label: 'Building Entrance', src: '/listings/101/25-building-entrance.jpeg' },
    ],
    rates: rates(415),
    cleaningRon: 120,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchenette', 'Elevator',
      'Hair dryer', 'Heating', 'Smart TV with Netflix', 'Dedicated workspace',
      'Private entrance', 'Self check-in',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi', 'Dedicated workspace'],
      'Location Features': ['Private entrance (separate street entrance)'],
      'Parking & Facilities': ['Elevator', 'Paid street parking off premises', 'Single level home', 'No stairs in home'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed', 'Full kitchen', 'Washer', 'Carbon monoxide alarm'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Cotton linens', 'Iron', 'Drying rack for clothing', 'Clothing storage: closet and wardrobe'],
      'Entertainment': ['Ethernet connection', '42 inch HDTV with Netflix, premium cable'],
      'Family': ['Paid crib — available upon request (mini size)'],
      'Heating & Cooling': ['Air conditioning', 'Central heating'],
      'Home Safety': ['Smoke alarm', 'Fire extinguisher'],
      'Kitchen & Dining': ['Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Mini fridge', 'Freezer', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Kitchenette', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Paid public parking is available on the street nearby. Reservation is not needed.' },
      { q: 'How far is the Old Town?', a: 'The Old Town is literally at your doorstep — a 2-minute walk from the building entrance. You\'re at the gateway to Bucharest\'s most vibrant district.' },
      { q: 'Is the apartment suitable for longer stays?', a: 'Yes, long-term stays of 28 days or more are welcome. The kitchenette is fully equipped for self-catering, and housekeeping is available at extra cost.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.1 km' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '1.3 km' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '1.4 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '1.8 km' },
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '2 km' },
      { category: 'Top Attractions', name: 'Bucharest Botanical Garden', distance: '3 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum', distance: '3.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '3.6 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '3.7 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '5 km' },
      { category: 'Restaurants & Cafés', name: 'Abel\'s Wine Bar', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'The Artist', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Anika', distance: '50 m' },
      { category: 'Public Transit', name: 'Piata Unirii Metro Station', distance: '700 m' },
      { category: 'Public Transit', name: 'Piața Unirii 2', distance: '750 m' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '2.8 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '3.6 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '8 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '16 km' },
    ],
    reviews: [
      { author: 'Eleana', date: 'December 2025', rating: 5, body: 'Thank you very much for the stay. The apartment was centrally located which helped us walk to various important monuments. Very good communication with the hosts who gave us tips on places worth visiting. Highly recommend!' },
      { author: 'Cezara', date: 'October 2025', rating: 5, body: 'Such a lovely place! It\'s so hard to find a quiet apartment in this area with good sleep. Sparkling clean, comfy bed, fresh towels and everything you need. There is a fridge, TV with Netflix, iron, hair dryer — perfect for being in the heart of the city. Highly recommended!' },
      { author: 'Simona', date: 'August 2025', rating: 5, body: 'Very lovely place for a quick getaway, very close to the best part of town, terraces, clubs, all the fun you can get. Easy to check in, responsive host, lovely recommendations. Overall great stay.' },
      { author: 'Florin', date: 'August 2025', rating: 5, body: 'Very nice, clean, small and cute apartment located right downtown next to Old Town in Bucharest. Definitely recommend for anyone looking to visit for a couple of days. The host was very responsive. We\'re going to stay here again.' },
      { author: 'Adina Ioana', date: 'August 2025', rating: 5, body: 'The apartment is extremely well maintained. Super cozy and very clean. Beautiful surroundings with places to walk and very good restaurants. I highly recommend this flat and the owners are really nice people. Loved it and I would come back.' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '102',
    slug: 'the-modern-beige-deluxe',
    name: 'The Modern Beige Deluxe',
    subtitle: 'AVEXA Suite 102',
    tagline: sharedTagline,
    neighborhood: 'calea-victoriei',
    neighborhoodLabel: nbh['calea-victoriei'].label,
    neighborhoodColor: nbh['calea-victoriei'].color,
    building: 'cv142',
    address: 'Calea Victoriei 142-148, Sector 1, Bucharest',
    stats: [
      { icon: 'users', label: '2 Guests' },
      { icon: 'bed', label: 'Studio' },
      { icon: 'sofa', label: '1 Double Bed' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 2,
    metaDescription:
      'A quiet garden-view studio on Calea Victoriei with digital check-in and a compact kitchenette — a peaceful Bucharest city center apartment, sleeps 2.',
    description:
      'A garden-facing studio set directly on Calea Victoriei, insulated from the boulevard while the city\'s best restaurants, shops, and coffee sit outside the door. Lush green installations, a double bed with premium linens, and a spa-style shower cabin set the tone; an in-unit washer and dryer plus a full kitchenette make longer stays effortless.',
    goodToKnow:
      'House notes: quiet hours run 22:00–08:00 and parties are strictly prohibited. The apartment is smoke-free — smoking indoors or on the balcony incurs a €500 ozone cleaning fee — and is fitted with smart smoke detectors.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/102/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/102/00-cover.jpeg' },
      { id: 2, label: 'Living Room', src: '/listings/102/01-living-room.jpeg' },
      { id: 3, label: 'Living Room — Wide', src: '/listings/102/01a-living-room-wide.jpeg' },
      { id: 4, label: 'Green Wall Desk', src: '/listings/102/02-green-wall-desk.jpeg' },
      { id: 5, label: 'Bedroom', src: '/listings/102/08-bedroom.jpeg' },
      { id: 6, label: 'Kitchen', src: '/listings/102/07-kitchen.jpeg' },
      { id: 7, label: 'Bathroom', src: '/listings/102/06-bathroom.jpeg' },
      { id: 8, label: 'Decor Shelf', src: '/listings/102/05-decor-shelf.jpeg' },
      { id: 9, label: 'Green Wall Detail', src: '/listings/102/09-green-wall-detail.jpeg' },
      { id: 10, label: 'Window View', src: '/listings/102/11-window-view.jpeg' },
      { id: 11, label: 'Wall Art Detail', src: '/listings/102/12-wall-art-detail.jpeg' },
      { id: 12, label: 'Living Room — Alt', src: '/listings/102/13-living-room-alt.jpeg' },
    ],
    rates: rates(479),
    cleaningRon: 120,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchenette', 'Washer & Dryer',
      'Garden view', 'Hair dryer', 'Heating', 'Smart TV with Netflix',
      'Elevator', 'Self check-in',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi', 'Dedicated workspace'],
      'Parking & Facilities': ['Elevator', 'Paid street parking off premises', 'Single level home', 'No stairs in home'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed', 'Full kitchen', 'Private entrance', 'Carbon monoxide alarm'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Washer', 'Free dryer — In unit', 'Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Cotton linens', 'Iron', 'Clothing storage: closet and wardrobe'],
      'Entertainment': ['Ethernet connection', 'Smart TV with Netflix, premium cable'],
      'Heating & Cooling': ['Air conditioning', 'Central heating'],
      'Home Safety': ['Smoke alarm', 'Fire extinguisher'],
      'Kitchen & Dining': ['Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Mini fridge', 'Freezer', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Induction stove', 'Kitchenette', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Free street parking is available nearby on Calea Victoriei. Paid street parking off premises is also available. No reservation needed.' },
      { q: 'Is the apartment quiet?', a: 'Yes — the studio faces the building\'s interior garden rather than the boulevard, making it one of the quietest units on Calea Victoriei.' },
      { q: 'Is the apartment suitable for longer stays?', a: 'Yes, long-term stays of 28 days or more are welcome. The kitchenette is fully equipped for self-catering, with an in-unit washer and dryer, and housekeeping is available at extra cost.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '100 m' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '800 m' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '850 m' },
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.2 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum', distance: '1.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '1.7 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '3.2 km' },
      { category: 'Top Attractions', name: 'Ceausescu Mansion', distance: '3.4 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '3.5 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '3.7 km' },
      { category: 'Restaurants & Cafés', name: 'French Bakery', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Cascara Coffee Roaster', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Eden Bistro', distance: '50 m' },
      { category: 'Public Transit', name: 'Piata Romana Metro Station', distance: '600 m' },
      { category: 'Public Transit', name: 'Piața Victoriei 1', distance: '1.2 km' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '1.7 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '2.5 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '7 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '15 km' },
    ],
    reviews: [],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '201',
    slug: 'the-golden-forest',
    name: 'The Golden Forest',
    subtitle: 'AVEXA Suite 201',
    tagline: sharedTagline,
    neighborhood: 'old-city-center',
    neighborhoodLabel: nbh['old-city-center'].label,
    neighborhoodColor: nbh['old-city-center'].color,
    building: 'cv2',
    address: 'Calea Victoriei Nr. 2, Sector 3, Bucharest',
    stats: [
      { icon: 'users', label: '4 Guests' },
      { icon: 'bed', label: '1 Bedroom' },
      { icon: 'sofa', label: '2 Beds' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 4,
    metaDescription:
      'A botanical one-bedroom in the Adriatica Palace — soundproofed King bedroom, Dâmbovița River views, sleeps 4. Bucharest city center, digital check-in.',
    description:
      'A one-bedroom in the Palace of the "Adriatica" Society, overlooking the Dâmbovița River with the Old Town beginning at your doorstep. The completely soundproofed bedroom holds a King-size bed; the botanical living room adds a Queen sofa bed, hosting four in total. A walk-in shower with LED lighting and a full kitchen with dishwasher and oven complete the suite.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/201/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/201/00-cover.jpeg' },
      { id: 2, label: 'Bathroom', src: '/listings/201/06-bathroom-green.jpeg' },
      { id: 3, label: 'Bathroom Full', src: '/listings/201/10-bathroom-full.jpeg' },
      { id: 4, label: 'Hallway', src: '/listings/201/19-hallway-entrance.jpeg' },
      { id: 5, label: 'Hallway Wide', src: '/listings/201/23-hallway-wide.jpeg' },
      { id: 6, label: 'Building Door', src: '/listings/201/25-building-door.jpeg' },
      { id: 7, label: 'Building Hall', src: '/listings/201/26-building-hall.jpeg' },
      { id: 8, label: 'Building Hall', src: '/listings/201/27-building-hall2.jpeg' },
      { id: 9, label: 'Exterior View', src: '/listings/201/29-exterior-view.jpeg' },
      { id: 10, label: 'Living Room', src: '/listings/201/32-apartment-view.jpeg' },
      { id: 11, label: 'Staircase', src: '/listings/201/34-staircase.jpeg' },
    ],
    rates: rates(572),
    cleaningRon: 150,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchen', 'Elevator',
      'Washer', 'Hair dryer', 'Heating', 'Dishwasher',
      'HDTV with Netflix', 'Private entrance',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi', 'Dedicated workspace'],
      'Location Features': ['Private entrance (separate street entrance)'],
      'Outdoor': ['Patio or balcony'],
      'Parking & Facilities': ['Elevator', 'Paid street parking off premises'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Cleaning products', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Washer', 'Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Cotton linens', 'Extra pillows and blankets', 'Room-darkening shades', 'Iron', 'Drying rack for clothing', 'Clothing storage: closet'],
      'Entertainment': ['Ethernet connection', 'HDTV with Netflix, premium cable', 'Exercise equipment'],
      'Family': ['Paid crib — available upon request (mini size)', 'Children\'s books and toys (ages 0–5)', 'Paid high chair — available upon request'],
      'Heating & Cooling': ['Air conditioning', 'Central heating'],
      'Home Safety': ['Smoke alarm', 'Carbon monoxide alarm', 'Fire extinguisher', 'First aid kit'],
      'Kitchen & Dining': ['Kitchen', 'Refrigerator', 'Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Freezer', 'Dishwasher', 'Stainless steel induction stove', 'Double oven', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Dining table', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Paid public parking is available on the street nearby at Piata Națiunilor parking, just across the street. Reservation is not needed.' },
      { q: 'Is there a river view?', a: 'Yes — the apartment overlooks the Dâmbovița River, offering panoramic views from the living area. You are positioned at the gateway to the Old Town.' },
      { q: 'Is the apartment family-friendly?', a: 'Yes. A crib (25 lei/night) and high chair are available upon request. Children of all ages are welcome. Children 6+ are charged as adults.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.1 km' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '1.3 km' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '1.4 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '1.8 km' },
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '2 km' },
      { category: 'Top Attractions', name: 'Bucharest Botanical Garden', distance: '3 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum', distance: '3.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '3.6 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '3.7 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '5 km' },
      { category: 'Restaurants & Cafés', name: 'Abel\'s Wine Bar', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'The Artist', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Anika', distance: '50 m' },
      { category: 'Public Transit', name: 'Piata Unirii Metro Station', distance: '700 m' },
      { category: 'Public Transit', name: 'Piața Unirii 2', distance: '750 m' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '2.8 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '3.6 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '8 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '16 km' },
    ],
    reviews: [
      { author: 'Julie', date: 'May 2026', rating: 5, body: 'Traditional apartment in the heart of the City. Seconds away from all the sights and surrounded by shops, cafes and bars which made everything so easy. The apartment is large and comfortable and the espresso machine with good coffee was a real plus!' },
      { author: 'Cris', date: 'May 2026', rating: 5, body: 'Absolutely amazing place, this was the second time I stayed here and I will return in the future for sure. Walking distance to so many places, from the Old Town, to the shopping center, subway. Clean, beautiful place with everything you need and more inside.' },
      { author: 'Brittany', date: 'April 2026', rating: 5, body: 'Great Location! Old town restaurants & shopping are located right outside your door. Despite being located at a busy intersection, the apartment is quiet. I am a light sleeper and I slept great. The apartment is beautiful, completely updated and comfortable.' },
      { author: 'Andie', date: 'May 2026', rating: 5, body: 'We really enjoyed our stay here in the heart of Bucharest. The location is greatly placed to explore the sights around the old town. The apartment is well equipped and smartly furnished. It has everything you need for a city break. Loved our trip!' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '202',
    slug: 'the-modern-green-gem',
    name: 'The Modern Green Gem',
    subtitle: 'AVEXA Suite 202',
    tagline: sharedTagline,
    neighborhood: 'calea-victoriei',
    neighborhoodLabel: nbh['calea-victoriei'].label,
    neighborhoodColor: nbh['calea-victoriei'].color,
    building: 'cv142',
    address: 'Calea Victoriei 142-148, Sector 1, Bucharest',
    stats: [
      { icon: 'users', label: '4 Guests' },
      { icon: 'bed', label: '1 Bedroom' },
      { icon: 'sofa', label: '2 Beds' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 4,
    metaDescription:
      'One-bedroom directly on Calea Victoriei — two private balconies, Știrbey Palace views, 65-inch TV, sleeps 4. Digital check-in, Bucharest city center.',
    description:
      'Two private balconies look straight onto Calea Victoriei and the Știrbey Palace from this one-bedroom for four. Inside: a queen bed on a premium orthopedic mattress, a convertible sofa for extra guests, a 65-inch screen for movie nights, and a fully equipped kitchen with dishwasher and oven. Morning coffee comes with a palace view.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/202/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/202/00-cover.jpeg' },
      { id: 2, label: 'Bedroom', src: '/listings/202/04-bedroom.jpeg' },
      { id: 3, label: 'Bedroom Closet', src: '/listings/202/05a-bedroom-closet.jpeg' },
      { id: 4, label: 'Bathroom', src: '/listings/202/07-bathroom.jpeg' },
      { id: 5, label: 'Kitchen', src: '/listings/202/09-kitchen.jpeg' },
      { id: 6, label: 'Hallway', src: '/listings/202/12-hallway.jpeg' },
      { id: 7, label: 'Interior Courtyard', src: '/listings/202/32-courtyard.jpeg' },
      { id: 8, label: 'Open Streets Festival', src: '/listings/202/33-open-streets.jpeg' },
      { id: 9, label: 'Restaurant Nearby', src: '/listings/202/37-restaurant.jpeg' },
    ],
    rates: rates(730),
    cleaningRon: 150,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchen', 'Elevator',
      'Washer & Dryer', 'Hair dryer', 'Heating', 'Dishwasher',
      '65" TV', 'Balcony',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi', 'Dedicated workspace'],
      'Outdoor': ['Private patio or balcony'],
      'Parking & Facilities': ['Free street parking', 'Elevator', 'Paid street parking off premises', 'Single level home', 'No stairs in home'],
      'Services': ['Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed', 'Carbon monoxide alarm', 'Private entrance'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Cleaning products', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Washer', 'Free dryer', 'Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Cotton linens', 'Extra pillows and blankets', 'Room-darkening shades', 'Iron', 'Drying rack for clothing', 'Clothing storage: closet'],
      'Entertainment': ['Ethernet connection', '65 inch TV'],
      'Family': ['Crib', 'Children\'s books and toys (ages 0–5)', 'Paid high chair — available upon request'],
      'Heating & Cooling': ['Window AC unit', 'Heating'],
      'Home Safety': ['Smoke alarm', 'Fire extinguisher'],
      'Kitchen & Dining': ['Kitchen', 'Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Freezer', 'Dishwasher', 'Induction stove', 'Oven', 'Hot water kettle', 'Wine glasses', 'Toaster', 'Dining table', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Free street parking is available nearby. Paid street parking is also available off premises. No reservation needed.' },
      { q: 'Does the apartment have a balcony?', a: 'Yes — two private balconies overlooking Calea Victoriei and the beautiful Stirbey Palace landscape.' },
      { q: 'Is there a view?', a: 'Stunning panoramic views of Stirbey Palace from both private balconies. The apartment is located directly on Calea Victoriei, Bucharest\'s most iconic boulevard.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '100 m' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '800 m' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '850 m' },
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.2 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum', distance: '1.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '1.7 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '3.2 km' },
      { category: 'Top Attractions', name: 'Ceausescu Mansion', distance: '3.4 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '3.5 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '3.7 km' },
      { category: 'Restaurants & Cafés', name: 'French Bakery', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Cascara Coffee Roaster', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Eden Bistro', distance: '50 m' },
      { category: 'Public Transit', name: 'Piata Romana Metro Station', distance: '600 m' },
      { category: 'Public Transit', name: 'Piața Victoriei 1', distance: '1.2 km' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '1.7 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '2.5 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '7 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '15 km' },
    ],
    reviews: [
      { author: 'Ariela', date: 'March 2026', rating: 5, body: 'The flat was absolutely spotless and well equipped. The location is great! Walking distance or a very quick uber to most places. The area itself is great with lots of lovely cafes and restaurants and shops. The hosts were lovely, very helpful and responsive. Would highly recommend!' },
      { author: 'Jamee', date: 'April 2026', rating: 5, body: 'Perfect home away from home, it\'s just as described. Very nice touch providing kids toys. Very easy to access and very close to all the restaurants, cafes etc. I\'ll for sure stay here again the next time I\'m in Bucharest.' },
      { author: 'Uldis', date: 'April 2026', rating: 5, body: 'Great apartment, with all necessary equipment, clean and tidy. Great location. Recommend.' },
      { author: 'Jason', date: 'February 2026', rating: 5, body: 'Super comfortable apartment with modern amenities in a very accessible area on Calea Victoriei with great restaurants and cafes in every direction. The perfect place to stay. The hosts are amazing. Extremely responsive, understanding, and friendly. Hope to stay here again!' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '203',
    slug: 'the-modern-quartz-gem',
    name: 'The Modern Quartz Gem',
    subtitle: 'AVEXA Suite 203',
    tagline: sharedTagline,
    neighborhood: 'universitate',
    neighborhoodLabel: nbh['universitate'].label,
    neighborhoodColor: nbh['universitate'].color,
    building: 'coltei25',
    address: 'Colței Street 25, Sector 3, Bucharest',
    stats: [
      { icon: 'users', label: '4 Guests' },
      { icon: 'bed', label: '1 Bedroom' },
      { icon: 'sofa', label: '2 Beds' },
      { icon: 'bath', label: '2 Bathrooms' },
    ],
    maxGuests: 4,
    metaDescription:
      'A quiet one-bedroom near Universitate, 2 minutes from Old Town — rare two bathrooms, sleeps 4. Bucharest city center apartment with digital check-in.',
    description:
      'Two minutes from the Old Town and a short walk from Universitate metro, this one-bedroom pairs a supremely quiet Queen bedroom with a rarity among central Bucharest rentals: two contemporary bathrooms, one with a walk-in shower and one with a cabin shower. High-speed Wi-Fi, dedicated climate control, and a gourmet kitchen with premium coffee machine complete a genuinely restful base.',
    goodToKnow: 'Situated on an elevated ground floor — just 5 steps up from the entrance — this apartment perfectly combines easy access for your luggage with enhanced privacy. Located steps away from the vibrant Old Town, it serves as a remarkably quiet urban oasis, ensuring a peaceful and restful night\'s sleep inside.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/203/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/203/00-cover.jpeg' },
      { id: 2, label: 'Living Room', src: '/listings/203/01a-living-room.jpeg' },
      { id: 3, label: 'Living & Kitchen', src: '/listings/203/01b-living-room.jpeg' },
      { id: 4, label: 'Bedroom', src: '/listings/203/02-bedroom.jpeg' },
      { id: 5, label: 'Bedroom — Wardrobe', src: '/listings/203/03-bedroom-wardrobe.jpeg' },
      { id: 6, label: 'Kitchen & Dining', src: '/listings/203/04-kitchen.jpeg' },
      { id: 7, label: 'Kitchen', src: '/listings/203/05a-kitchen-sink.jpeg' },
      { id: 8, label: 'Bathroom 1', src: '/listings/203/05b-bathroom1.jpeg' },
      { id: 9, label: 'Bathroom 1 — Vanity', src: '/listings/203/06-bathroom1-basins.jpeg' },
      { id: 10, label: 'Bathroom 2', src: '/listings/203/07-bathroom2.jpeg' },
    ],
    rates: rates(677),
    cleaningRon: 150,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchen', 'Elevator',
      'Washer', 'Hair dryer', 'Heating', 'Dishwasher',
      'TV', 'Private entrance',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi'],
      'Location Features': ['Private entrance (separate street entrance)'],
      'Parking & Facilities': ['Elevator', 'Paid street parking off premises', 'Single level home', 'No stairs in home'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Cleaning products', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Washer', 'Hangers', 'Bed linens', 'Extra pillows and blankets', 'Room-darkening shades', 'Iron', 'Drying rack for clothing', 'Clothing storage'],
      'Entertainment': ['Ethernet connection', 'TV', 'Books and reading material'],
      'Family': ['Paid crib — available upon request', 'Children\'s books and toys (ages 0–5)', 'Paid high chair — available upon request'],
      'Heating & Cooling': ['Air conditioning', 'Central heating'],
      'Home Safety': ['Smoke alarm', 'Carbon monoxide alarm', 'Fire extinguisher'],
      'Kitchen & Dining': ['Kitchen', 'Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Freezer', 'Dishwasher', 'Induction stove', 'Oven', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Dining table', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Paid public parking is available on the street nearby. Reservation is not needed.' },
      { q: 'How far is the nearest metro station?', a: 'Universitate Metro Station is just 500 meters away — roughly a 5-minute walk. Piata Unirii 2 is 1 km away.' },
      { q: 'Is the apartment noisy given its central location?', a: 'Despite being in the heart of the city, the apartment is remarkably quiet. Quality soundproof windows ensure almost no street noise reaches inside, making it an ideal urban oasis for restful sleep.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Revolution Square', distance: '1.1 km' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '1.5 km' },
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.6 km' },
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '2.2 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '2.7 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum of Natural History', distance: '3.3 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '3.4 km' },
      { category: 'Top Attractions', name: 'Bucharest Botanical Garden', distance: '3.9 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '4.3 km' },
      { category: 'Top Attractions', name: 'Alexandru Ioan Cuza Park', distance: '4.8 km' },
      { category: 'Restaurants & Cafés', name: 'Slow Restaurant', distance: '10 m' },
      { category: 'Restaurants & Cafés', name: 'The Legend Café', distance: '10 m' },
      { category: 'Restaurants & Cafés', name: 'Underworld Bar', distance: '20 m' },
      { category: 'Public Transit', name: 'Universitate Metro Station', distance: '500 m' },
      { category: 'Public Transit', name: 'Piața Unirii 2 Metro Station', distance: '1 km' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '3.4 km' },
      { category: 'Public Transit', name: 'Obor Station', distance: '3.5 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '8 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '16 km' },
    ],
    reviews: [
      { author: 'Viktoria', date: 'May 2026', rating: 5, body: 'Amazing apartment and very helpful. Cozy, well-equipped and spotless. Even though it is on the first floor, windows are good enough to soundproof the place, so almost no noise was coming in from the street.' },
      { author: 'Ilinca-Adina', date: 'April 2026', rating: 5, body: 'I had a great stay! The apartment is beautiful and the bed is super comfortable. Top location too, just steps from the old town. I felt like home and will definitely be back!' },
      { author: 'Mihai', date: 'April 2026', rating: 5, body: 'Centrally located. Beautiful modern apartment. Wonderful attentive host.' },
      { author: 'Carsten', date: 'May 2026', rating: 5, body: 'Was a very nice place to stay and a super host. Thank you again.' },
      { author: 'Gabriela', date: 'April 2026', rating: 5, body: 'A ten-star stay! The apartment is fantastic, it\'s impeccable, and it has absolutely everything you need. We really felt at home. The location is unbeatable: a very quiet area but at the same time super central, ideal for getting around on foot. A 10/10 for the hosts!' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '301',
    slug: 'ultracentral-gem-calea-victoriei',
    name: 'The Ultracentral Gem Calea Victoriei & Palace View',
    subtitle: 'AVEXA Suite 301',
    tagline: sharedTagline,
    neighborhood: 'calea-victoriei',
    neighborhoodLabel: nbh['calea-victoriei'].label,
    neighborhoodColor: nbh['calea-victoriei'].color,
    building: 'cv142',
    address: 'Calea Victoriei, Sector 1, Bucharest',
    stats: [
      { icon: 'users', label: '6 Guests' },
      { icon: 'bed', label: '2 Bedrooms' },
      { icon: 'sofa', label: '3 Beds' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 6,
    // name + subtitle would render a 83-char title; keep the SERP title <60.
    metaTitle: 'The Ultracentral Gem — Calea Victoriei',
    metaDescription:
      'Two-bedroom apartment for six with calming views over Calea Victoriei — dining for 6, family-ready. Bucharest city center, digital check-in.',
    description:
      'A two-bedroom residence for six with calming views over Calea Victoriei, surrounded by fine restaurants, stylish shops, and major attractions. A queen-size bedroom, a second bedroom that converts to a queen, and a sofa bed gather around a dining table for six; the kitchen runs from oven to dishwasher, and a baby crib and child seat are available on request.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/301/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Living Room & Dining', src: '/listings/301/00-cover.jpeg' },
      { id: 2, label: 'Hallway', src: '/listings/301/09-hallway.jpeg' },
      { id: 3, label: 'Bedroom 2', src: '/listings/301/11-bedroom2.jpeg' },
      { id: 4, label: 'Bedroom 1', src: '/listings/301/15-bedroom1.jpg' },
      { id: 5, label: 'Kitchen', src: '/listings/301/16-kitchen.jpg' },
      { id: 6, label: 'Bathroom', src: '/listings/301/19-bathroom.jpeg' },
      { id: 7, label: 'Washer & Dryer', src: '/listings/301/19b-washer.jpg' },
      { id: 8, label: 'Palace View', src: '/listings/301/20-palace-view.jpeg' },
      { id: 9, label: 'Street View', src: '/listings/301/23-street-view.jpg' },
      { id: 10, label: 'Courtyard Garden', src: '/listings/301/25-courtyard.jpg' },
      { id: 11, label: 'Living Room', src: '/listings/301/30-living-room.jpeg' },
      { id: 12, label: 'Bedroom 2 View', src: '/listings/301/31-bedroom2-view.jpeg' },
      { id: 13, label: 'Interior Courtyard', src: '/listings/301/32-interior-courtyard.jpeg' },
      { id: 14, label: 'Open Streets Festival', src: '/listings/301/33-open-streets.jpeg' },
      { id: 15, label: 'Restaurant Nearby', src: '/listings/301/37-restaurant.jpeg' },
    ],
    rates: rates(782),
    cleaningRon: 180,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Parking', 'Free Wi-Fi', 'Family rooms', 'Non-smoking rooms',
      'Elevator', 'Heating', 'Air conditioning', 'Kitchen',
      'Washer & Dryer', 'Dishwasher',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi'],
      'Location Features': ['Private entrance (separate street entrance)'],
      'Parking & Facilities': ['Free street parking', 'Elevator', 'Paid street parking off premises', 'Single level home', 'No stairs in home'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Exterior security cameras', 'Carbon monoxide alarm'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Cleaning products', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Washer', 'Free dryer — In unit', 'Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Extra pillows and blankets', 'Room-darkening shades', 'Iron', 'Drying rack for clothing', 'Clothing storage'],
      'Entertainment': ['Ethernet connection', '74 inch HDTV with Netflix, premium cable'],
      'Family': ['Paid crib — available upon request', 'Children\'s books and toys', 'Paid high chair — available upon request', 'Children\'s dinnerware'],
      'Heating & Cooling': ['Air conditioning', 'Heating'],
      'Home Safety': ['Smoke alarm', 'Fire extinguisher'],
      'Kitchen & Dining': ['Kitchen', 'Refrigerator', 'Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Freezer', 'Dishwasher', 'Stainless steel gas stove', 'Oven', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Public parking is available at a location nearby (reservation is not needed) and costs 30 lei per day.' },
      { q: 'Do they serve breakfast?', a: 'There\'s no breakfast option available.' },
      { q: 'What are the check-in and check-out times?', a: 'Check-in from 15:00 to 22:00. Check-out until 11:00. If you\'d like to request an early or late check-in or check-out, you can make a special request when you book.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '100 m' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '800 m' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '850 m' },
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.2 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum', distance: '1.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '1.7 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '3.2 km' },
      { category: 'Top Attractions', name: 'Ceausescu Mansion', distance: '3.4 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '3.5 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '3.7 km' },
      { category: 'Restaurants & Cafés', name: 'French Bakery', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Cascara Coffee Roaster', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Eden Bistro', distance: '50 m' },
      { category: 'Public Transit', name: 'Piata Romana Metro Station', distance: '600 m' },
      { category: 'Public Transit', name: 'Piața Victoriei 1', distance: '1.2 km' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '1.7 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '2.5 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '7 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '15 km' },
    ],
    reviews: [],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '302',
    slug: 'the-modern-sapphire-gem',
    name: 'The Modern Sapphire Gem',
    subtitle: 'AVEXA Suite 302',
    tagline: sharedTagline,
    neighborhood: 'calea-victoriei',
    neighborhoodLabel: nbh['calea-victoriei'].label,
    neighborhoodColor: nbh['calea-victoriei'].color,
    building: 'cv142',
    address: 'Calea Victoriei 142-148, Sector 1, Bucharest',
    stats: [
      { icon: 'users', label: '6 Guests' },
      { icon: 'bed', label: '2 Bedrooms' },
      { icon: 'sofa', label: '3 Beds' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 6,
    metaDescription:
      'Elegant two-bedroom on Calea Victoriei with Știrbei Palace views and a quiet green courtyard — sleeps 6. Digital check-in, Bucharest city center.',
    description:
      'An elegant two-bedroom on Calea Victoriei where the windows frame the Știrbei Palace and a quiet green courtyard waits at the back of the building. A queen master and a second double bedroom sleep families or groups of up to six, joined by a 164 cm smart TV, a six-person dining table, and a walk-in shower with premium finishes.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/302/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/302/00-cover.jpeg' },
      { id: 2, label: 'Living Room', src: '/listings/302/02-living-room.jpeg' },
      { id: 3, label: 'Bedroom 1', src: '/listings/302/04-bedroom1.jpeg' },
      { id: 4, label: 'Bedroom 2', src: '/listings/302/08-bedroom2.jpeg' },
      { id: 5, label: 'Kitchen', src: '/listings/302/10-kitchen.jpeg' },
      { id: 6, label: 'Bathroom', src: '/listings/302/12-bathroom.jpeg' },
      { id: 7, label: 'Interior Courtyard', src: '/listings/302/32-courtyard.jpeg' },
      { id: 8, label: 'Open Streets Festival', src: '/listings/302/33-open-streets.jpeg' },
      { id: 9, label: 'Restaurant Nearby', src: '/listings/302/37-restaurant.jpeg' },
    ],
    rates: rates(730),
    cleaningRon: 180,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchen', 'Elevator',
      'Free washer', 'Hair dryer', 'Heating', '75" HDTV with Netflix',
      'Dedicated workspace', 'Self check-in',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi', 'Dedicated workspace'],
      'Parking & Facilities': ['Free street parking', 'Elevator', 'Paid parking off premises', 'Single level home', 'No stairs in home'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed', 'Carbon monoxide alarm', 'Private entrance'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Cleaning products', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Free washer — In unit', 'Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Cotton linens', 'Extra pillows and blankets', 'Room-darkening shades', 'Iron', 'Drying rack for clothing', 'Clothing storage: closet and wardrobe'],
      'Entertainment': ['Ethernet connection', '75 inch HDTV with Netflix, premium cable'],
      'Family': ['Paid crib — available upon request', 'Children\'s books and toys (ages 0–5)', 'Paid high chair — available upon request', 'Children\'s dinnerware'],
      'Heating & Cooling': ['Air conditioning', 'Central heating'],
      'Home Safety': ['Smoke alarm', 'Fire extinguisher'],
      'Kitchen & Dining': ['Kitchen', 'Refrigerator', 'Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Freezer', 'Induction stove', 'Oven', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Dining table', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Free street parking is available nearby. Paid parking is also available off premises. No reservation needed.' },
      { q: 'How far is the nearest metro?', a: 'Piata Romana Metro Station is 600 meters away — roughly a 7-minute walk. Piața Victoriei 1 is 1.2 km.' },
      { q: 'Is the apartment family-friendly?', a: 'Yes. A crib (25 lei/night) and high chair are available upon request. Children of all ages are welcome. We provide children\'s books, toys, dinnerware, and colorful plastic dishes and cutlery.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '100 m' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '800 m' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '850 m' },
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.2 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum', distance: '1.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '1.7 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '3.2 km' },
      { category: 'Top Attractions', name: 'Ceausescu Mansion', distance: '3.4 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '3.5 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '3.7 km' },
      { category: 'Restaurants & Cafés', name: 'French Bakery', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Cascara Coffee Roaster', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Eden Bistro', distance: '50 m' },
      { category: 'Public Transit', name: 'Piata Romana Metro Station', distance: '600 m' },
      { category: 'Public Transit', name: 'Piața Victoriei 1', distance: '1.2 km' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '1.7 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '2.5 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '7 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '15 km' },
    ],
    reviews: [
      { author: 'Ona', location: 'Tirana, Albania', date: 'March 2026', rating: 5, body: 'This cozy, centrally located apartment was perfect for my family. The beds were comfortable, even the couch was a spacious, supportive mattress for one of our teenagers. Walk to the old town in 25 minutes, many restaurants and grocery stores closer.' },
      { author: 'Rosie', date: 'May 2026', rating: 5, body: 'The place is spacious, sparkling clean, and in a great location. It is packed with thoughtful touches of amenities (equipped kitchen, coffee stations, high-speed Wi-Fi, smart TVs, laundry facilities) that really help make your stay very comfortable. Highly recommended!' },
      { author: 'Karen', date: 'March 2026', rating: 5, body: 'Vlad\'s apartment was in a neighbourhood with plenty of shops, bars and restaurants and was less than 20 minutes on foot to the Old Town. The apartment was clean and the bedrooms were good sizes. Plenty of towels available per guest too.' },
      { author: 'Emilia', date: 'January 2026', rating: 5, body: 'The apartment has an amazing design and looks better than in the photos. It was spotless clean and very cozy. Has also a very good location, next to restaurants, shops and touristic sites. The hosts are very good communicators! 100% recommend!' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '303',
    slug: 'the-modern-oak-gem',
    name: 'The Modern Oak Gem',
    subtitle: 'AVEXA Suite 303',
    tagline: sharedTagline,
    neighborhood: 'calea-victoriei',
    neighborhoodLabel: nbh['calea-victoriei'].label,
    neighborhoodColor: nbh['calea-victoriei'].color,
    building: 'cv142',
    address: 'Calea Victoriei 142-148, Sector 1, Bucharest',
    stats: [
      { icon: 'users', label: '6 Guests' },
      { icon: 'bed', label: '2 Bedrooms' },
      { icon: 'sofa', label: '3 Beds' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 6,
    metaDescription:
      'Freshly renovated two-bedroom over Calea Victoriei — Queen and double suites plus a sofa bed, dining for 6. Bucharest city center, digital check-in.',
    description:
      'Freshly renovated in spring 2026, this two-bedroom sits directly over Calea Victoriei, Bucharest\'s most historic boulevard. A plush Queen suite, a cozy double bedroom, and a high-comfort sofa bed sleep six, gathered around a dining table made for long breakfasts. The full kitchen brings modern appliances, dishwasher and dryer included, for stays of any length.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/303/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/303/00-cover.jpeg' },
      { id: 2, label: 'Bedroom 1', src: '/listings/303/02a-bedroom1.jpeg' },
      { id: 3, label: 'Bedroom 1 Closet', src: '/listings/303/02b-bedroom1-closet.jpeg' },
      { id: 4, label: 'Bedroom 2', src: '/listings/303/04b-bedroom2.jpeg' },
      { id: 5, label: 'Bedroom 2', src: '/listings/303/05-bedroom2-chairs.jpeg' },
      { id: 6, label: 'Kitchen', src: '/listings/303/07-kitchen.jpeg' },
      { id: 7, label: 'Bathroom', src: '/listings/303/08-bathroom.jpeg' },
      { id: 8, label: 'Living Room', src: '/listings/303/09-living-room.jpeg' },
    ],
    rates: rates(782),
    cleaningRon: 180,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchen', 'Elevator',
      'Washer & Dryer', 'Hair dryer', 'Heating', 'Dishwasher',
      'HDTV with Netflix', 'Private entrance',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi', 'Dedicated workspace'],
      'Location Features': ['Private entrance (separate street entrance)'],
      'Parking & Facilities': ['Elevator', 'Paid street parking off premises', 'Single level home'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Cleaning products', 'Shampoo', 'Body soap', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Washer', 'Free dryer — In unit', 'Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Extra pillows and blankets', 'Room-darkening shades', 'Iron', 'Drying rack for clothing', 'Clothing storage'],
      'Entertainment': ['Ethernet connection', 'HDTV with Netflix, premium cable'],
      'Family': ['Paid crib — available upon request', 'Children\'s toys'],
      'Heating & Cooling': ['Air conditioning', 'Central heating'],
      'Home Safety': ['Smoke alarm', 'Fire extinguisher'],
      'Kitchen & Dining': ['Kitchen', 'Refrigerator', 'Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Freezer', 'Dishwasher', 'Stove', 'Oven', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Dining table', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Ample public paid parking is available on all surrounding streets. No reservation needed.' },
      { q: 'How close is public transit?', a: 'Piata Romana Metro Station is 600 meters away. Piața Victoriei 1 is 1.2 km. Bucharest North Railway Station is 1.7 km.' },
      { q: 'Is the apartment family-friendly?', a: 'Yes. A crib is available upon request (25 lei/night). Children of all ages are welcome. Children 6+ are charged as adults. Toys are provided for little ones.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '100 m' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '800 m' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '850 m' },
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '1.2 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum', distance: '1.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '1.7 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '3.2 km' },
      { category: 'Top Attractions', name: 'Ceausescu Mansion', distance: '3.4 km' },
      { category: 'Top Attractions', name: 'National Museum Cotroceni', distance: '3.5 km' },
      { category: 'Top Attractions', name: 'Carol Park', distance: '3.7 km' },
      { category: 'Restaurants & Cafés', name: 'French Bakery', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Cascara Coffee Roaster', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Eden Bistro', distance: '50 m' },
      { category: 'Public Transit', name: 'Piata Romana Metro Station', distance: '600 m' },
      { category: 'Public Transit', name: 'Piața Victoriei 1', distance: '1.2 km' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '1.7 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '2.5 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '7 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '15 km' },
    ],
    reviews: [
      { author: 'Roxana', date: 'March 2026', rating: 5, body: 'We had a wonderful stay at this beautiful apartment. It is fully equipped and spotless clean. We enjoyed the awesome bathroom and smart shower. Very relaxing! Host is friendly and called to make sure we have everything we need. 100% recommend!' },
      { author: 'Emanuel', date: 'March 2026', rating: 5, body: 'The apartment is very beautiful and spacious, brand new and with a comfortable bed. We enjoyed the view & our baby boy the provided toys. Thanks for a great stay! We will come back.' },
      { author: 'Olga', date: 'May 2026', rating: 5, body: 'We had a wonderful stay. The interior design is thoughtful, harmonious, and very pleasant. The apartment was exceptionally clean with all necessary amenities: coffee machine, fridge, dishes, washing machine, and dishwasher. The hosts had even prepared coffee and tea, which was a lovely touch.' },
      { author: 'Raya', date: 'May 2026', rating: 5, body: 'Great location, super clean, and very comfortable. Communication was easy and check-in was seamless. Highly recommend!' },
      { author: 'Ilinca-Adina', date: 'March 2026', rating: 5, body: 'A very nice new apartment with a lovely host. Clear check-in instructions & a comfortable bright workspace. I will definitely come back!' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  {
    id: '304',
    slug: 'central-quiet-luxury',
    name: 'Central Quiet Luxury',
    subtitle: 'AVEXA Suite 304',
    tagline: sharedTagline,
    neighborhood: 'piata-romana',
    neighborhoodLabel: nbh['piata-romana'].label,
    neighborhoodColor: nbh['piata-romana'].color,
    building: 'polona115',
    address: 'Polonă Street, Sector 1, Bucharest',
    stats: [
      { icon: 'users', label: '6 Guests' },
      { icon: 'bed', label: '2 Bedrooms' },
      { icon: 'sofa', label: '3 Beds' },
      { icon: 'bath', label: '1 Bathroom' },
    ],
    maxGuests: 6,
    metaDescription:
      'Quiet two-bedroom for six by Piața Romană — steps from the metro, 10 minutes\' walk to Calea Victoriei. Digital check-in, Bucharest city center.',
    description:
      'A quiet two-bedroom for six near Piața Romană, steps from the metro and a ten-minute walk from Calea Victoriei. A queen-size master and a comfortable double suite anchor an expansive living area with a dining zone for six, and the equipped kitchen — dishwasher, premium coffee maker — handles slow mornings and long stays alike.',
    checkin: sharedCheckin,
    checkout: sharedCheckout,
    cover: '/listings/304/00-cover.jpeg',
    photos: [
      { id: 1, label: 'Cover', src: '/listings/304/00-cover.jpeg' },
      { id: 2, label: 'Living Room', src: '/listings/304/01-living-room.jpeg' },
      { id: 3, label: 'Bedroom 1', src: '/listings/304/02-bedroom1.jpeg' },
      { id: 4, label: 'Bedroom 1 — Workspace', src: '/listings/304/03-bedroom1-desk.jpeg' },
      { id: 5, label: 'Bedroom 2', src: '/listings/304/04-bedroom2.jpeg' },
      { id: 6, label: 'Hallway', src: '/listings/304/05-hallway.jpeg' },
      { id: 7, label: 'Kitchenette', src: '/listings/304/06a-kitchenette.jpeg' },
      { id: 8, label: 'Coffee Station', src: '/listings/304/06b-coffee-station.jpeg' },
      { id: 9, label: 'Bathroom', src: '/listings/304/07-bathroom.jpeg' },
      { id: 10, label: 'Shower', src: '/listings/304/08-shower.jpeg' },
      { id: 11, label: 'Washer', src: '/listings/304/09-washer.jpeg' },
      { id: 12, label: 'Kids Area', src: '/listings/304/10-kids-area.jpeg' },
      { id: 13, label: 'Baby Crib', src: '/listings/304/11-baby-crib.jpeg' },
      { id: 14, label: 'Terrace', src: '/listings/304/12-terrace.jpeg' },
      { id: 15, label: 'Street View', src: '/listings/304/13-street-view.jpeg' },
    ],
    rates: rates(625),
    cleaningRon: 180,
    upgrades: baseUpgrades,
    amenitiesTop: [
      'Free Wi-Fi', 'Air conditioning', 'Kitchen', 'Elevator',
      'Free washer', 'Hair dryer', 'Heating', 'Dedicated workspace',
      'Smart TV with Netflix', 'Private entrance',
    ],
    amenitiesProperty: {
      'Internet & Office': ['Wi-Fi', 'Dedicated workspace'],
      'Location Features': ['Private entrance (separate street entrance)', 'Laundromat nearby'],
      'Outdoor': ['Private backyard — fully fenced', 'Outdoor furniture', 'Outdoor dining area'],
      'Parking & Facilities': ['Free street parking', 'Elevator', 'Paid street parking off premises', 'Single level home', 'No stairs in home'],
      'Services': ['Luggage dropoff allowed', 'Long term stays allowed', 'Self check-in (Lockbox)', 'Housekeeping — available at extra cost'],
      'Not Included': ['Pets not allowed', 'Carbon monoxide alarm', 'Full kitchen'],
    },
    amenitiesRoom: {
      'Bathroom': ['Hair dryer', 'Cleaning products', 'Shampoo', 'Body soap', 'Bidet', 'Hot water', 'Shower gel'],
      'Bedroom & Laundry': ['Free washer — In unit', 'Essentials (towels, bed sheets, soap, toilet paper)', 'Hangers', 'Bed linens', 'Cotton linens', 'Extra pillows and blankets', 'Iron', 'Drying rack for clothing', 'Mosquito net', 'Clothing storage: closet'],
      'Entertainment': ['Ethernet connection', '65 inch HDTV with Netflix, premium cable'],
      'Family': ['Paid crib — available upon request', 'Children\'s books and toys (ages 0–5)', 'Paid high chair — available upon request', 'Children\'s dinnerware', 'Window guards', 'Outdoor playground'],
      'Heating & Cooling': ['Window AC unit', 'Central heating'],
      'Home Safety': ['Smoke alarm', 'Fire extinguisher', 'First aid kit'],
      'Kitchen & Dining': ['Microwave', 'Cooking basics (pots, pans, oil, salt & pepper)', 'Dishes and silverware', 'Mini fridge', 'Freezer', 'Induction stove', 'Single oven', 'Hot water kettle', 'Coffee maker (drip)', 'Wine glasses', 'Toaster', 'Kitchenette', 'Dining table', 'Coffee'],
    },
    faqs: [
      { q: 'Can I park there?', a: 'Public parking is available at a location nearby (reservation is not needed) and costs 30 lei per day.' },
      { q: 'How far is the nearest metro station?', a: 'Stefan cel Mare Metro Station is just 450 meters away — roughly a 4-minute walk. Piata Romana is 1.1 km away.' },
      { q: 'Is this apartment suitable for families with children?', a: 'Absolutely. The apartment sleeps up to 6, and a baby crib and high chair are available upon request. We also have children\'s books, toys, dinnerware, and window guards.' },
    ],
    nearby: [
      { category: 'Top Attractions', name: 'Museum of Art Collections', distance: '1.5 km' },
      { category: 'Top Attractions', name: 'Grigore Antipa National Museum of Natural History', distance: '1.6 km' },
      { category: 'Top Attractions', name: 'Museum of Romanian Peasant', distance: '1.7 km' },
      { category: 'Top Attractions', name: 'Revolution Square', distance: '1.8 km' },
      { category: 'Top Attractions', name: 'National Museum of Art of Romania', distance: '1.9 km' },
      { category: 'Top Attractions', name: 'Cismigiu Gardens', distance: '2.4 km' },
      { category: 'Top Attractions', name: 'Ceausescu Mansion', distance: '2.5 km' },
      { category: 'Top Attractions', name: 'Bucharest Arch of Triumph', distance: '2.9 km' },
      { category: 'Top Attractions', name: 'Dimitrie Gusti National Village Museum', distance: '3.4 km' },
      { category: 'Top Attractions', name: 'Herastrau Park', distance: '4.3 km' },
      { category: 'Restaurants & Cafés', name: 'Chic Meniu', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: 'Bake A Coffee', distance: '50 m' },
      { category: 'Restaurants & Cafés', name: '5 To Go', distance: '50 m' },
      { category: 'Public Transit', name: 'Stefan cel Mare Metro Station', distance: '450 m' },
      { category: 'Public Transit', name: 'Piata Romana Metro Station', distance: '1.1 km' },
      { category: 'Public Transit', name: 'Bucharest North Railway Station', distance: '2.5 km' },
      { category: 'Public Transit', name: 'Gara Basarab', distance: '3.2 km' },
      { category: 'Closest Airports', name: 'Băneasa Airport', distance: '5 km' },
      { category: 'Closest Airports', name: 'Henri Coandă International Airport', distance: '14 km' },
    ],
    reviews: [
      { author: 'Marius', date: 'March 2026', rating: 5, body: 'Great stay overall! The hosts were very responsive and helpful, especially with our late arrival and flexible check-in. Clear instructions made everything easy, and communication was smooth throughout. The apartment was comfortable and suited our needs, even traveling with a baby.' },
      { author: 'Anne', location: 'Tel Aviv, Israel', date: 'February 2026', rating: 5, body: 'We had a perfect time in this apartment. It is very spacious and comfortable and actually looks even better than the photos. The beds were very comfortable and the house was very clean and warm.' },
      { author: 'Codrin', date: 'January 2026', rating: 5, body: 'I had a great stay! The apartment is very beautiful (better than in the photos), clean, very quiet and with a very comfortable bed. I have received very clear check-in instructions with pictures. Friendly and warm hosts!' },
      { author: 'Alex', date: 'November 2025', rating: 5, body: 'We had a wonderful stay at this very nice spacious and super clean apartment! Perfect for family with kids. Perfect location, bedrooms to the backside, very quiet.' },
      { author: 'Delia', date: 'October 2025', rating: 5, body: 'Absolutely loved our stay! The place was clean, cozy, and had everything we needed. The host was super friendly and easy to communicate with. We felt right at home and would definitely come back again.' },
      { author: 'Albert', location: 'Islip, New York', date: 'September 2025', rating: 5, body: 'Probably the best value stay I\'ve ever booked on Airbnb compared to other options. The host went above and beyond to ensure our comfort. It\'s a brand new apartment and has many items included.' },
      { author: 'Codrin', date: 'August 2025', rating: 5, body: 'A newly renovated apartment, better than in the photos, a great surprise when I got there! Relaxing, with nature themes, very clean and super quiet. The mattress was extremely comfortable. Great hosts, very involved to offer a great service.' },
    ],
  },
];

export function getProperty(idOrSlug: string): Property | undefined {
  return properties.find((p) => p.id === idOrSlug || p.slug === idOrSlug);
}

export function getPropertiesByNeighborhood(n: NeighborhoodId): Property[] {
  return properties.filter((p) => p.neighborhood === n);
}

export function getAllPropertyIds(): string[] {
  return properties.map((p) => p.id);
}
